### ISSUE TITLE
Time deltas are inconsistent with "Elm time"

### ISSUE THREAD

**Issue by jvoigtlaender** [jwmerrill/elm-animation-frame#6]
I think that in

``` elm
Signal.foldp (\(new,delta) (_,old,_) -> (new-old,new,delta)) (0,0,0) (Time.timestamp AnimationFrame.frame)
```

the proper semantics would be that on the resulting signal the first and third triple component are always equal to each other (except in the first event that fires, for setup reasons).

The current behavior is far from that. (The first and third triple component are often very different.)

**Comment by jwmerrill** [comment]
Is this causing a bug in something you're building?

I chose to use the time passed in by requestAnimationFrame instead of using Time.timestamp because it's more accurate and it's consistent between different callbacks that fire on the same animation frame.

The inconsistency isn't great, and it would be reasonably easy for me to switch to Time.timestamp. Alternatively, I think that maybe Time.timestamp should be adjusted to work more like what I'm doing here.

Longer term, I don't think it really makes sense to maintain this library separately from the core runtime forever. I think either we should decide to get this into core, or replace it with something different in core. It's kind of painful that this library breaks the Reactor (#1), and I'm not sure it's super realistic that we'll be able to make them work well together with this as a library.

**Comment by jwmerrill** [comment]
If you have time/interest in putting together a PR that makes this work the way you think it should work, I would strongly consider merging it. I don't really have specific use cases that require the current behavior, so if you've got something that requires the behavior you're proposing, that's probably good evidence that we should be doing that instead.

**Comment by jvoigtlaender** [comment]
I'm not depending on the specifics at the moment. I use `AnimationFrame.frame` as a drop-in replacement for `Time.fps` when available (i.e., when teaching in an environment where I can rely on people having a local installation rather than having to use http://elm-lang.org/try).

While learning more about `requestAnimationFrame` during looking into an issue about `elm-effects`, I realized that `requestAnimationFrame` is using its own notion of time (since start of program instead of since start of epoch), and started to wonder what else that means in relation to compatibility of the timing from this library to other timing in Elm. Which led me to the observations in my opening comment above.

So I don't really come with evidence that anything must be changed. The current behavior hasn't caused trouble for me yet. It's more a theoretical concern that `AnimationFrame.frame` and `Time.fps` are not actually as semantically interchangeable as I thought.

In general, I agree that it would be good to bring support for `requestAnimationFrame` into `core` directly. And then, I would feel stronger about the need for compatibility of notions of time involved.

I might still come up with a pull request here. In the meantime, it should already be possible to do the `timestamp`ing (and subsequent `foldp`ing to reconstruct deltas) in client code. So maybe it's enough for now to just document the behavior. This GitHub issue might serve this purpose, or maybe even a sentence in the package's documentation itself?
